name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - name: Harden Runner
              uses: step-security/harden-runner@0d381219ddf674d61a7572ddd19d7941e271515c # v2.9.0
              with:
                egress-policy: audit

            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
            - uses: gautamkrishnar/blog-post-workflow@ba49e6584c153fc9dc2d43e02bc30bdb2a6b1b07 # master
              with: 
                max_post_count: "4"
                feed_list: "https://paolozaino.wordpress.com/feed/"