name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - name: Harden Runner
              uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
              with:
                egress-policy: audit

            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
            - uses: gautamkrishnar/blog-post-workflow@ccb6032125dc5032b8b4f70a355479a3d76902f4 # master
              with: 
                max_post_count: "4"
                feed_list: "https://paolozaino.wordpress.com/feed/"