name: Latest blog post workflow
on: 
    schedule:
        - cron: '0 * * * *'
jobs: 
    update-readme-with-blog: 
        name: Update this repo's README with latest blog posts
        runs-on: ubuntu-latest
        steps: 
            - name: Harden Runner
              uses: step-security/harden-runner@5c7944e73c4c2a096b17a9cb74d65b6c2bbafbde # v2.9.1
              with:
                egress-policy: audit

            - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
            - uses: gautamkrishnar/blog-post-workflow@5669a0d7d58de027f74e51bf4fc5dd73ceabc254 # master
              with: 
                max_post_count: "4"
                feed_list: "https://paolozaino.wordpress.com/feed/"